<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$config['categories']= array(
    'MEN'=>array(
        'Tanks',
        'Bags & Wallets','Bags & Wallets'=>array('Backpacks','Briefcases','Messenger bags','Wallets'),
        'Belts & Buckles',
        'Bottoms','Bottoms'=>array('Pants','Shorts','Swim','Underwear'),
        'Coats & Jackets','Coats & Jackets'=>array('Blazers','Coats','Jackets'),
        'Cufflinks',
        'Hats',
        'Shirts',
        'Shoes',
        'Suits',
        'Sweaters',
        'T-Shirts',
        'Ties', 
        'Clips & Bow Ties',
        'Other Clothing',
        'Other Accessories'

    ),
    'WOMEN'=>array(
        'Accessories','Accessories'=>array('Belts','Eyewear','Gloves & Mittens','Hats Legwear','Scarves','Watches','Shoe Accessories'),
        'Bags & Purses',
        
    ),
    'BOTTOMS'=>array(
        'Jeans',
        'Jumpsuits',
        'Leggings',
        'Pants',
        'Shorts & Capris',
        'Skirts',
        'Yoga Pants',
    ),
    'DRESSES'=>array(
        'Day',
        'Evening & Prom',
        'Little Black Dresses',
        'Maxi',
        'Party',
        'Vintage',
        
    ),
    'OUTWEAR'=>array(
        'Capes',
        'Coates',
        'Jackets & Blazers',
        'Vests',

     ),
    'SHOES'=>array(
        'Athletic',
        'Boots',
        'Clogs',
        'Flats',      
        'Heels & Pumps',
        'Shoe Accessories',
        'Slippers',
        'Wedges',   
    ),
    //Sleepwear & Intimates
    'SI'=>array(
        'Capes',
        'Coates',
        'Jackets & Blazers',
        'Vests',
        'Bras',
        'Camis & Tanks',
        'Corsets',
        'Lingerie Accessories',
        'Lingerie Sets',
        'Nightgowns',
        'Pajamas',
        'Panties',  
        'Robes',
        'Slips',
       
    ),
    //Swimwear & Coverups
    'SC'=>array(
        'Coverups',
        'One-Piece',
        'Two-Piece',     
    ),
    'TOPS'=>array(
        'Blouses',
        'Hoodies & Sweatshirts',
        'Sweaters & Cardigans',
        'T-Shirts', 
        'Tank Tops', 
        'Tunics',       
        'Vests', 
        'Wrap Tops',
    ),
    'ART'=>array(
        'Custom Portraits',
        'Decorative Arts',
        'Drawing & Illistrations',
        'Figurines & Art Objects',
        'Painting',
        'Photography',
        'Prints & Posters',
        'Sculpture',
        ),
    //Home & Living
    'HL'=>array(
        'Bath & Beauty',
        'Books, Music & Media',
        'Collectibles',
        'Decor & Housewares',
        'Dining & Entertaining',
        'Electronics & Gadgets',
        'Furniture',
        'Kitchen',
        'Lighting',
        'Musical Instruments',
        'Outdoors & Garden',
        'Pets',
        'Stationary & Party',
        'Storage & Organization'),
    //Mobile Accessories
    'MA'=>array(
        'Decals',
        'Docking Stations & Chargers',
        'Flash Drives',
        'Gear for Android',
        'Gear for Kindle',
        'Gear for Ipad Mini',
        'Gear for Ipad',
        'Gear for Iphone',
        'Headphones',
        'Keyboard Accessories',
        'Laptop Bags',
        'Laptop Cases',
        'Phone Cases & Wallets',
        'Phone Covers',
        'Phone Plugs & Charms',
        'Speakers',
        'Stands',
        'Styluses',
        'Tablet Accessories'),
    'Jewelry'=>array(
        'Body',
        'Bracelets',
        'Brooches',
        'Earrings',
        'Eco-Friendly',
        'Fine Jewelry',
        'Kids',
        'Men',
        'Necklace',
        'Personalized',
        'Rings',
        'Storage & Organization', 
        'Watches'),
    'Kids'=>array(
        'Baby & Toddler',
        'Bath',
        'Boys',
        'Costumes',
        'Eco-Friendly',
        'Furniture & Decor',
        'Girls',
        'Personalized',
        'School & Learning',
        'Special Occasions',
        'Toys'
     ),
    'Vintage'=>array(
        'Accessories',
        'Antiques',
        'Art',
        'Books',
        'Clothing',
        'Collectibles',
        'Furniture',
        'Home Decor' ,
        'Housewares',
        'Paper Ephemera',
        'Serving' ,
     ),
    'Toys'=>array(
            'Weddings',
            'Bridal Accessories',
            'Decor',
            'Dresses',
            'Groom',
            'Paper Goods',
            'Rings',
            'Wedding Party',
            'Registry',
    ),
    'Craft Supplies'=>array(
            'DIY Weddings',
            'Fine Arts',
            'Floral & Gardening',
            'Food Crafting',
            'Framing',
            'Gift Wrapping',
            'Jewelry Making',
            'Knitting & Crochet',
            'Paper Crafts',
            'Scrapbooking',
            'Sewing, Quilting & Needle Crafts',
            'Woodworking'
    ),

);


$config['categories_all']= array(
        'Tanks',
        'Bags & Wallets',//=>array('Backpacks','Briefcases','Messenger bags','Wallets'),
        'Belts & Buckles',
        'Bottoms',//=>array('Pants','Shorts','Swim','Underwear'),
        'Coats & Jackets',//=>array('Blazers','Coats','Jackets'),
        'Cufflinks',
        'Hats',
        'Shirts',
        'Shoes',
        'Suits',
        'Sweaters',
        'T-Shirts',
        'Ties', 
        'Clips & Bow Ties',
        'Other Clothing',
        'Other Accessories',
        'Accessories',//=>array('Belts','Eyewear','Gloves & Mittens','Hats Legwear','Scarves','Watches','Shoe Accessories'),
        'Bags & Purses',
        'Jeans',
        'Jumpsuits',
        'Leggings',
        'Pants',
        'Shorts & Capris',
        'Skirts',
        'Yoga Pants',
        'Day',
        'Evening & Prom',
        'Little Black Dresses',
        'Maxi',
        'Party',
        'Vintage',
        'Capes',
        'Coates',
        'Jackets & Blazers',
        'Vests',
        'Athletic',
        'Boots',
        'Clogs',
        'Flats',      
        'Heels & Pumps',
        'Shoe Accessories',
        'Slippers',
        'Wedges',   
        'Capes',
        'Coates',
        'Jackets & Blazers',
        'Vests',
        'Bras',
        'Camis & Tanks',
        'Corsets',
        'Lingerie Accessories',
        'Lingerie Sets',
        'Nightgowns',
        'Pajamas',
        'Panties',  
        'Robes',
        'Slips',
        'Coverups',
        'One-Piece',
        'Two-Piece',     
        'Blouses',
        'Hoodies & Sweatshirts',
        'Sweaters & Cardigans',
        'T-Shirts', 
        'Tank Tops', 
        'Tunics',       
        'Vests', 
        'Wrap Tops',
        'Custom Portraits',
        'Decorative Arts',
        'Drawing & Illistrations',
        'Figurines & Art Objects',
        'Painting',
        'Photography',
        'Prints & Posters',
        'Sculpture',
        'Bath & Beauty',
        'Books, Music & Media',
        'Collectibles',
        'Decor & Housewares',
        'Dining & Entertaining',
        'Electronics & Gadgets',
        'Furniture',
        'Kitchen',
        'Lighting',
        'Musical Instruments',
        'Outdoors & Garden',
        'Pets',
        'Stationary & Party',
        'Storage & Organization',
        'Decals',
        'Docking Stations & Chargers',
        'Flash Drives',
        'Gear for Android',
        'Gear for Kindle',
        'Gear for Ipad Mini',
        'Gear for Ipad',
        'Gear for Iphone',
        'Headphones',
        'Keyboard Accessories',
        'Laptop Bags',
        'Laptop Cases',
        'Phone Cases & Wallets',
        'Phone Covers',
        'Phone Plugs & Charms',
        'Speakers',
        'Stands',
        'Styluses',
        'Tablet Accessories',
        'Body',
        'Bracelets',
        'Brooches',
        'Earrings',
        'Eco-Friendly',
        'Fine Jewelry',
        'Kids Jewelry',
        'Men',
        'Necklace',
        'Personalized',
        'Rings',
        'Storage & Organization', 
        'Watches',
        'Baby & Toddler',
        'Bath',
        'Boys',
        'Costumes',
        'Eco-Friendly',
        'Furniture & Decor',
        'Girls',
        'Personalized',
        'School & Learning',
        'Special Occasions',
        'Toys',
        'Accessories',
        'Antiques',
        'Art',
        'Books',
        'Clothing',
        'Collectibles',
        'Furniture',
        'Home Decor' ,
        'Housewares',
        'Paper Ephemera',
        'Serving' ,
        'Weddings',
        'Bridal Accessories',
        'Decor',
        'Dresses',
        'Groom',
        'Paper Goods',
        'Rings',
        'Wedding Party',
        'Registry',
        'DIY Weddings',
        'Fine Arts',
        'Floral & Gardening',
        'Food Crafting',
        'Framing',
        'Gift Wrapping',
        'Jewelry Making',
        'Knitting & Crochet',
        'Paper Crafts',
        'Scrapbooking',
        'Sewing, Quilting & Needle Crafts',
        'Woodworking',
);